---
title: "heatmap_sql"
output: html_document
---

# Setup

```{r}
library(readxl)
library(DBI)
library(RSQLite)
```

```{r setup}
# Define connection to database (or create it if it doesn't exist)

riskdb_path <- "tridel.db"
heatxl_path <- "support_files/heatmap.xlsx"

db_conn <- dbConnect(RSQLite::SQLite(), dbname = riskdb_path)

knitr::opts_chunk$set(connection = "db_conn")
```

# Create tables

## Risks

```{sql}
CREATE TABLE risks (
  risk_number integer primary key,
  risk_name text,
  risk_description text,
  risk_impact integer,
  risk_probability integer
);
```

## Actions

```{sql}
CREATE TABLE actions (
  action_number integer primary key,
  risk_number integer REFERENCES risks (risk_number),
  action_description text,
  action_responsible text,
  action_deadline text,
  action_status text
);
```

# List all tables and fields
```{sql}
SELECT
  m.name AS table_name, 
  p.cid AS col_id,
  p.name AS col_name,
  p.type AS col_type,
  p.pk AS col_is_pk,
  p.dflt_value AS col_default_val,
  p.[notnull] AS col_is_not_null
FROM sqlite_master m
LEFT OUTER JOIN pragma_table_info((m.name)) p
  ON m.name <> p.name
WHERE m.type = 'table'
ORDER BY table_name, col_id
```

# Upload data

## Risks
```{r}
dbWriteTable(conn = db_conn,
             append = TRUE,
             name = "risks",
             value = read_xlsx(path = risks_path,
                               # sheet = "risks", 
                               na = "")
             )
```

## Actions

```{r}
dbWriteTable(conn = db_conn,
             append = TRUE,
             name = "actions",
             value = read_xlsx(path = heatxl_path,
                               sheet = "actions", 
                               na = "")
             )
```

# Insert data manually

```{sql}
INSERT INTO actions (action_number, risk_number) VALUES (1115, 2)


```



# Display data

## Risks
```{sql}
SELECT *
FROM "risks"
```

## Actions
```{sql}
SELECT *
FROM "actions"
```
# Delete data

## Risks
```{sql}
DELETE FROM risks
--WHERE risk_number = 1117
```

## Actions
```{sql}
DELETE FROM actions
```

```{sql}
DELETE FROM actions
WHERE action_number = NA
```


# Remove table

## Risks
```{sql}
DROP TABLE risks;
```

## Actions
```{sql}
DROP TABLE actions;
```

# Actions by user

```{sql}
SELECT actions.risk_number, risks.risk_description, actions.action_number, actions.action_responsible, actions.action_description
FROM actions
INNER JOIN risks
ON actions.risk_number = risks.risk_number
WHERE actions.action_responsible = "S.Odet"
```

# Disconnect database
```{r}
dbDisconnect(db_conn)
```











